name: Build and Deploy

on:
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v1
        with:
          ref: gh-pages
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: master
          clean: false
      
      - uses: actions/setup-node@v2
      
      - name: Install build dependencies
        run: npm install
      
      - name: Build
        run: grunt build
        env:
          TZ: America/Toronto
      
      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git branch --delete --force gh-pages
          git checkout --orphan gh-pages
          git add -f .
          git commit -m "Rebuild GitHub Pages"
          git push -f origin gh-pages
